db:
  image: postgres:9.4.1
  ports:
    - "5432:5432"

app:
  build: .
  ports:
    - "3000:3000"
  environment:
    - RAILS_ENV=production
    - ZIHER_DB_NAME=my_db_name
    - ZIHER_DB_USERNAME=my_db_username
    - ZIHER_DB_PASSWORD=my_db_password
  links:
    - db
