# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af541b95a18a6c4de4be3f38f5ec7ddb565fe3d0690f0f909de759fea7cb1e5760602be1488890c86259e72ebeca1a1290097289aa35bc74d469bb4d5457cbe2

test:
  secret_key_base: 99d943cea03d4e3e69098f4fcb4ea3665b1e19e0f8287455745276bd20c392df2dcd6d6bb243f2a2be3f1f291da066950c67986792580bd465dcf585492d13d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
